Changes date input to a date picker
jmuzy-sps/sps-spring21-team41 pull request #13
Opened 2021-04-03 02:46 UTC by valvarez1218

I changed the date input field to a date picker, but I am unsure if this will change any functionality with the server side in terms of adding the date to the database. It doesn't seem like it to me, but please let me know if this is an issue.

2021-04-03 18:25 UTC, jmuzy-sps requested changes

2021-04-03 18:25 UTC, jmuzy-sps commented on src/main/webapp/createEvent.html
> +                  <input type="text" name="date" id="date" placeholder="MM-dd-yyyy HH:mm"/> -->
Delete these lines if they're unused

2021-04-03 19:45 UTC, josh-hdz approved these changes

2021-04-04 14:39 UTC, jmuzy-sps approved these changes

2021-04-04 14:39 UTC, merged