Adds code to EventRetrievalServlet
jmuzy-sps/sps-spring21-team41 pull request #15
Opened 2021-04-03 03:20 UTC by valvarez1218

I don't know why I named the branch "RetrieveComments"
Regardless, I added code to the servlet so that it returns the necessary information to the javaScript function which will add the event information to the homepage. I need to test it with events in the database.

2021-04-03 18:28 UTC, jmuzy-sps requested changes
Nice job!

2021-04-03 18:28 UTC, jmuzy-sps commented on src/main/java/com/google/sps/servlets/EventRetrievalServlet.java
> +    Query.newEntityQueryBuilder().setKind("event").setOrderBy(OrderBy.desc("date")).build();
Indent this over so it's not inline with the above line

2021-04-03 19:44 UTC, josh-hdz approved these changes

2021-04-04 14:38 UTC, jmuzy-sps approved these changes

2021-04-04 14:38 UTC, merged