fix data types
jmuzy-sps/sps-spring21-team41 pull request #5
Opened 2021-03-30 17:40 UTC by josh-hdz

Location's zip code is not String due to possible leading zeros (ex. 023456).

Event now has a date(long) data member and price is float.

CreateEventServlet was modify to align with data types changes.

2021-03-30 17:44 UTC, josh-hdz commented on src/main/java/com/google/sps/servlets/CreateEventServlet.java
> +        long date = request.getParameter("date");
I assume these values are sent as float and long and no further processing is needed. If not this will create problems.

2021-03-30 19:30 UTC, jmuzy-sps requested changes

2021-03-30 19:30 UTC, jmuzy-sps commented on src/main/java/com/google/sps/data/Event.java
> +    private long date           // Epoch format
missing semi-colon

2021-03-30 19:30 UTC, jmuzy-sps commented on src/main/java/com/google/sps/data/Event.java
> +    public Event(String type, String details, float price, long date, Location address) {
I don't think it matters here, but I think generally with Java you prefer to use `double` instead of `float`

2021-03-30 19:30 UTC, jmuzy-sps commented on src/main/java/com/google/sps/data/Event.java
> +    public long getDate(){
I would add a comment with this function saying it returns the date as the number of seconds since the epoch. You have it where the variable is defined, but it also helps to have it here too

2021-03-30 19:30 UTC, jmuzy-sps commented on src/main/java/com/google/sps/servlets/CreateEventServlet.java
> +        long date = request.getParameter("date");
Thanks for pointing this out - it'll be something to keep an eye out for when hooking everything together

2021-03-30 21:33 UTC, jmuzy-sps approved these changes
Thanks Josh!

2021-03-31 18:34 UTC, valvarez1218 approved these changes
Everything looks fine to me, just wondering why we decided on a double instead of a float for the price? Do we expect that that much memory will be necessary?
Besides that, all looks good! Thanks Josh!

2021-03-31 18:53 UTC, josh-hdz commented
I don't know hahaha I just listen to the pros. It might be because of precision. There are some decimals that cannot be represented in binary (ex 0.1) so the value is saved as an approximation (ex. 0.1000000000000019) more bits make the value closer to the desire value.

2021-03-31 18:53 UTC, merged

2021-03-31 19:10 UTC, jmuzy-sps commented
I recommended the double over the float, because I think that's just what you generally do in Java. I don't know if memory is much of a concern here, but definitely a good thing to keep in mind with general coding. Also, I'm definitely not a pro, haha, and especially not in Java. There's always plenty more to learn :)